apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: portal-shell-in-a-box-ir
  labels:
    {{- include "event-operator.labels" . | nindent 4 }}
  {{ if .Values.global.ingressClass }}    
  annotations: 
    kubernetes.io/ingress.class: {{ .Values.global.ingressClass }}
  {{ end }}
spec:
  entryPoints:
  - {{ .Values.shellInABox.ingressRoute.entryPoint }}
  routes:
  - match: Host(`{{ .Values.shellInABox.ingressRoute.prefix }}.{{ .Values.global.baseUrl }}`)
    kind: Rule
    priority: {{ .Values.shellInABox.ingressRoute.priority }}
    services:
    - name: portal-shell-in-a-box-srv
      port:  {{ .Values.shellInABox.service.port }}
  {{ if .Values.shellInABox.ingressRoute.certResolver }}    
  tls:
    certResolver: {{ .Values.shellInABox.ingressRoute.certResolver }}
  {{ end }}