apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-code-server-cm
data:
  config.yaml: |-
    bind-addr: 127.0.0.1:8080
    auth: password
    password: {{ .Values.codeServer.password }}
    cert: false