apiVersion: v1
kind: Service
metadata:
  name: portal-code-server-srv
  labels:
    {{- include "event-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.codeServer.service.type }}
  ports:
    - port: {{ .Values.codeServer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "event-operator.selectorLabels" . | nindent 4 }}
    app: code-server
