apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: kube-system

spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 8080
    - protocol: TCP
      name: websecure
      port: 443
      targetPort: 8443
    - protocol: TCP
      name: admin
      port: 8080
      targetPort: 9090
  selector:
    app: traefik
  externalTrafficPolicy: Local
  type: LoadBalancer

