apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-single-sec
type: kubernetes.io/basic-auth
stringData:
  username: john
  password: topsecret42

---
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-multi-sec
data:
# sabine:topsecret123
# thomas:topsecret456
  users: |2
    dGhvbWFzOiRhcHIxJG1PazVxczFPJHVobE9aVFY4N2EzUFdSVkQyWWpqQy4NCnNh
    YmluZTokYXByMSRRS1kzVnpqVyQ2eFFqR1liOHk0WlBpZDJEenozTzgvDQ==
---

