name: "custom event portal operator"

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'Event-Operator/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: event-operator

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: |
        dotnet restore Event-Operator/src/Event-Operator.csproj
    - name: Build
      run: |
        dotnet build --no-restore Event-Operator/src/Event-Operator.csproj
    - name: Publish amd 64
      run: |
        dotnet publish -c release -r linux-x64 --no-self-contained -o Event-Operator/amd64 Event-Operator/src/Event-Operator.csproj
    - name: Publish arm 64
      run: |
        dotnet publish -c release -r linux-arm64 --no-self-contained -o Event-Operator/arm64 Event-Operator/src/Event-Operator.csproj
  
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=2.0.0
          type=raw,value=latest

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./Event-Operator
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}


