name: "custom hpa app"

on:
  push:
    branches: [ main ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: |
        dotnet restore Custom-HPA/Manager/Manager.csproj
        dotnet restore Custom-HPA/Worker/Worker.csproj
    - name: Build
      run: |
        dotnet build --no-restore Custom-HPA/Manager/Manager.csproj
        dotnet build --no-restore Custom-HPA/Worker/Worker.csproj
    - name: Publish
      run: |
        dotnet publish -c release -o Custom-HPA/Manager/out/ Custom-HPA/Manager/Manager.csproj
        dotnet publish -c release -o Custom-HPA/Worker/out/ Custom-HPA/Worker/Worker.csproj

    - name: Login to GHCR
      uses: docker/login-action@v2.1.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Extract metadata worker
      id: meta_worker
      uses: docker/metadata-action@v4
      with:
         images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}
         tags: |
           type=raw,value=hpa-worker

    - name: Extract metadata manager
      id: meta_manager
      uses: docker/metadata-action@v4
      with:
         images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}
         tags: |
           type=raw,value=hpa-manager

    - name: Build and push worker
      uses: docker/build-push-action@v3
      with:
        context: ./Custom-HPA/Worker/
        push: true
        tags: ${{ steps.meta_worker.outputs.tags }}
        labels: ${{ steps.meta_worker.outputs.labels }}
      
    - name: Build and push manager
      uses: docker/build-push-action@v3
      with:
        context: ./Custom-HPA/Manager/
        push: true
        tags: ${{ steps.meta_manager.outputs.tags }}
        labels: ${{ steps.meta_manager.outputs.labels }}


